<?= $this->getContent() ?>

<section class="col-md-8 col-lg-9">
	<h1>Auxiliary Compartment view</h1>
	<div class="rowOne">
		<article class="col-md-12 col-lg-12">
			<img src="img/DamageControlCenter.jpg" alt="dcc"/>
		</article>
		
	<div class="rowTwo">
		<article class="col-md-4 col-lg-4">
			Auxiliary Compartment or more popular as Damage Control Center is the place where the damage control reaction team is assembled. There are located control consoles for life support systems too. 
		</article>
		
		<article class="col-md-4 col-lg-4">
			<ul>Agenda: 
			<li>dco1 - damage control operator position 1</li> 
			<li>dco2 - damage control operator position 2</li>
			<li>dco3 - damage control operator position 3</li>
			<li>dcl - damage control leader</li>
		</article>
		
		<article class="col-md-4 col-lg-4">
			<li>lss1 - life support system position 1</li> 
			<li>lss2 - life support system position 2</li> 
			<li>lss3 - life support system position 3</li> 
			</ul> 
		</article>
		