<?= $this->getContent() ?>

<section class="col-md-8 col-lg-9">
	<h1>Bridge view</h1>
	<div class="row">
		<article class="col-md-6 col-lg-6">
			<img src="img/bridgeScheme-sm.jpg" alt="bridge"/>
		</article>
		
	<div class="row">
		<article class="col-md-6 col-lg-4">
			Bridge is the Reserve Command and Control center of the ship. It is equiped with consoles for navigation, engine control, life support and energy generation systems observation, firefighting and ship integrity observation. There is a visual observation of the space in vicinity via the observant hatches.
		</article>
		
		<article class="col-md-6 col-lg-4">
			<ul>Agenda: 
			<li>for - direction ahead of the ship</li> 
			<li>astern - direction back side of the ship</li>
			<li>fp - position of the First Pilot</li>
			<li>ce - position of the engineers team member</li>
			<li>co - position of the commanding officer</li> 
			<li>cm - crew member</li></ul> 
		</article>
		
		
		
		
		
		
		
</section>
