<?= $this->getContent() ?>

<section class="col-md-8 col-lg-9">
	<h1>Command and Control Center view</h1>
	<div class="rowOne">
		<article class="col-md-12 col-lg-12">
			Command and Control center is the main compartment onboard. It is maximum protected and equiped.
			<img src="img/C2Scheme.jpg" alt="C2"/>
		</article>
	<div class="row">
		
		<article class="col-md-6 col-lg-4">
			<ul>Agenda: 
			<li>for - direction ahead of the ship</li> 
			<li>astern - direction back side of the ship</li>
			<li>co - position of the commanding officer</li>
			<li>exo - position of the executive officer</li>
			<li>ce - position of the chief engineer</li>
		</article>
		<article class="col-md-6 col-lg-4">
			<li>commso - position of the communications officer</li>	
			<li>navo - position of the navigation officer</li>
			<li>sco - position of the science officer</li>
			<li>navop - position of the navigation operator</li>
			<li>scop - position of the science operator</li>
			<li>dc - position of the damage control officer</li>		
		</article>
		<article class="col-md-6 col-lg-4">
			<li>pco - position of the propulsion control officer</li>
			<li>eco - position of the energy control officer</li>
			<li>lsco - position of the life support system control officer</li>
			<li>ecop - position of the energy control operator</li>
			</ul> 
		</article>
		
		
		
</section>
