<?= $this->getContent() ?>

<section class="col-md-8 col-lg-9">
	<h1>Engine Control Room view</h1>
	<div class="rowOne">
		<article class="col-md-12 col-lg-12">
			<img src="img/MainEnginesControlRoom-sm.jpg" alt="ccs"/>
		</article>
		
	<div class="rowTwo">
		<article class="col-md-6 col-lg-4">
			Engine Control Center is the place, where the ship's energy supplies and Unified Propulsion Instalations System (UPIS) is commanded. This is the heart of the ship.  
		</article>
		
		<article class="col-md-6 col-lg-4">
			<ul>Agenda: 
			<li>en1 - energy supply control position 1</li> 
			<li>en2 - energy supply control position 2</li>
			<li>en3 - energy supply control position 3</li>
			</article>
			<article class="col-md-6 col-lg-4">
			<li>me1 - main and engines control position 1</li>
			<li>me2 - main and engines control position 2</li> 
			<li>me3 - main and engines control position 3</li> 
			<li>me4 - main and engines control position 4</li> 
			</ul> 
		</article>
		