<?= $this->getContent() ?>

<section class="col-md-8 col-lg-9">
	<h1>Observation room view</h1>
	<div class="rowOne">
		<article class="col-md-12 col-lg-12">
			<img src="img/ObservationRoom.jpg" alt="observe"/>
		</article>
		
	<div class="rowTwo">
		<article class="col-md-6 col-lg-4">
			Observation room is place, where one can enjoy looking outside via huge windows. This windows are more strong and resistent to the outside environment than the most tough steel with same dimensions.
		</article>
		
		<article class="col-md-6 col-lg-4">
			<ul>Agenda: 
			<li>op1 - observation position 1</li> 
			<li>op2 - observation position 2</li>
			<li>op3 - observation position 3</li>
			<li>op4 - observation position 4</li>
			<li>op5 - observation position 5</li> 
			<li>op6 - observation position 6</li> 
			<li>op7 - observation position 7</li> 
			<li>op8 - observation position 8</li> 
			</ul> 
		</article>
		