<?= $this->getContent() ?>

<section class="col-md-8 col-lg-9">
	<h1>Wardroom view</h1>
	<div class="rowOne">
		<article class="col-md-12 col-lg-12">
			<img src="img/wardroom1.jpg" alt="wardroom"/>
		</article>
		
	<div class="rowTwo">
		<article class="col-md-12 col-lg-12">
			Wardroom is the place where the crew members get together for meal, briefings, celebrations, etc. 
		</article>
		
		